# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-18 23:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appEncuesta', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='encuesta',
            name='nombreEncuesta',
            field=models.CharField(default='nombre', max_length=100),
        ),
    ]
