# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-21 15:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appEncuesta', '0004_remove_pregunta_cantidadrespuestas'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleEncuesta',
            fields=[
                ('idDetalleEncuesta', models.AutoField(primary_key=True, serialize=False)),
                ('fechaDetalle', models.DateField(auto_now=True)),
                ('idPregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appEncuesta.Pregunta')),
                ('idRespuesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appEncuesta.Respuesta')),
            ],
        ),
    ]
