# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-21 18:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appEncuesta', '0005_detalleencuesta'),
    ]

    operations = [
        migrations.AddField(
            model_name='respuesta',
            name='numeroRespuesta',
            field=models.IntegerField(default=None),
        ),
    ]
