# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-22 04:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appEncuesta', '0006_respuesta_numerorespuesta'),
    ]

    operations = [
        migrations.AddField(
            model_name='pregunta',
            name='numeroPregunta',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
