# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-22 07:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appEncuesta', '0007_pregunta_numeropregunta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='respuesta',
            name='tipoRespuesta',
        ),
    ]
