# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-25 13:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appEncuesta', '0008_remove_respuesta_tiporespuesta'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroIP',
            fields=[
                ('idRegistroIP', models.AutoField(primary_key=True, serialize=False)),
                ('ip', models.CharField(max_length=25)),
                ('fechaDetalle', models.DateField(auto_now=True)),
            ],
        ),
    ]
